[feat] : Software allocator가 추가된 decoder로 Bitmap반환
 java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps 오류 해결